name: Build and deploy to Releases
on: 
  push:
    branches:
      - master
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    env:
      minor_version: 1
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{GITHUB_RUN_ID}"
          replace: "${{ env.minor_version }}"
          include: "pbiviz.json" # Will match all README.md files in any nested directory
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{GITHUB_RUN_NUMBER}"
          replace: "${{ github.run_number }}"
          include: "pbiviz.json" # Will match all README.md files in any nested directory
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm install
      - run: npm run package
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/dist
      - run: |
          cat pbiviz.json
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.minor_version }}.${{ github.run_number }}
          files: |
            dist/PBI*.pbiviz
      - run: echo "🍏 This job's status is ${{ job.status }}."

